In [1]:
import numpy as np

In [28]:
arr=np.empty([4,2],dtype=np. uint16)


In [29]:
arr

array([[42624, 63847],
       [  376,     0],
       [    0,     0],
       [    0,     0]], dtype=uint16)

In [30]:
arr.shape

(4, 2)

In [31]:
arr.ndim

2

In [32]:
arr.itemsize

2

In [35]:
arr1=np.arange(100,200,10).reshape(5,2)

In [36]:
arr1

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [38]:
samplearray=np.array([[11,22,33],[44,55,66],[77,88,99]])

In [39]:
samplearray

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [54]:
samplearray[0:3,1]

array([22, 55, 88])

In [55]:
samplearray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

In [56]:
samplearray

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [59]:
samplearray[0::2,1::2]

array([[ 6, 12],
       [30, 36],
       [54, 60]])

In [60]:
arrayone = np.array([[5, 6, 9], [21 ,18, 27]])
arraytwo = np.array([[15 ,33, 24], [4 ,7, 1]])

In [65]:
arr2=arrayone+arraytwo

In [66]:
arr2

array([[20, 39, 33],
       [25, 25, 28]])

In [67]:
arr2**2

array([[ 400, 1521, 1089],
       [ 625,  625,  784]], dtype=int32)

In [68]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])

In [75]:
arr5=sampleArray

In [76]:
arr5

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [88]:
arr5[:,arr5[1,:].argsort()]

array([[73, 43, 34],
       [12, 22, 82],
       [66, 94, 53]])

In [86]:
arr5[arr5[:,1].argsort()]

array([[82, 22, 12],
       [34, 43, 73],
       [53, 94, 66]])